#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION=3.1.1
dl https://github.com/omeka/Omeka/releases/download/v$VERSION/omeka-$VERSION.zip /usr/local/src
