#!/bin/sh -ex

DB_NAME=omeka
DB_USER=omeka
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/omeka

# unpack and set permissions
unzip $SRC/omeka-*.zip -d $(dirname $WEBROOT)
rm $SRC/omeka-*.zip
mv $(dirname $WEBROOT)/omeka-* $WEBROOT
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/files

# configure db settings
cat >$WEBROOT/db.ini<<EOF
[database]
host     = "localhost"
username = "$DB_USER"
password = "$DB_PASS"
dbname   = "$DB_NAME"
prefix   = ""
charset  = "utf8"
;port     = ""
EOF
chown www-data:www-data $WEBROOT/db.ini
chmod 640 $WEBROOT/db.ini

# configure apache
a2dissite 000-default
a2ensite omeka
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/install/"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL $URL --data "username=$ADMIN_NAME&password=$ADMIN_PASS&password_confirm=$ADMIN_PASS&super_email=$EMAIL&administrator_email=$EMAIL&site_title=TurnKey+Omeka&description=&copyright=&author=&tag_delimiter=%2C&fullsize_constraint=800&thumbnail_constraint=200&square_thumbnail_constraint=200&per_page_admin=10&per_page_public=10&show_empty_elements=0&path_to_convert=%2Fusr%2Fbin&install_submit=Install"

rm -rf $WEBROOT/install
rm -f /tmp/cookie

# tweak footer
for footer in $WEBROOT/themes/*/common/footer.php; do
    sed -i "s|</body>|    <div id='turnkey-credit' style='text-align:center;font-size:11px;'><a href='https://www.turnkeylinux.org/omeka'>Omeka Appliance</a> - Powered by <a href='https://www.turnkeylinux.org'>TurnKey Linux</a></div>\n</body>|" $footer
done

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

