#!/bin/sh -ex

DB_NAME=omeka
DB_USER=omeka
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/omeka

# unpack and set permissions
unzip $SRC/omeka-*.zip -d $(dirname $WEBROOT)
rm $SRC/omeka-*.zip
mv $(dirname $WEBROOT)/omeka-* $WEBROOT
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/archive

# configure db settings
cat >$WEBROOT/db.ini<<EOF
[database]
host     = "localhost"
username = "$DB_USER"
password = "$DB_PASS"
dbname   = "$DB_NAME"
prefix   = ""
charset  = "utf8"
;port     = ""
EOF
chown www-data:www-data $WEBROOT/db.ini
chmod 640 $WEBROOT/db.ini

# configure apache
a2dissite default
a2ensite omeka
a2enmod rewrite

