#!/bin/bash -e
# regenerate omeka mysql password

. /etc/default/inithooks

CONF=/var/www/omeka/db.ini
PASSWORD=$(mcookie)
sed -i "s|password.*|password = \"$PASSWORD\"|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=omeka --pass="$PASSWORD"

